services:
  backend:
    build:
      context: ./services/backend
    volumes:
      - ./data/downloads:/app/data/downloads
      - ./data/db:/app/data/db
      - ./data/cache:/app/cache
    user: "${CURRENT_UID}:${CURRENT_GID}"
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - PORT=8080
      - DOWNLOAD_PATH=/app/data/downloads
      - DATABASE_PATH=/app/data/db/video-archiver.db
      - DEBUG=${DEBUG:-false}
      - XDG_CACHE_HOME=/app/cache
    develop:
      watch:
        - action: sync
          path: ./services/backend/cmd
          target: /app/cmd
        - action: sync
          path: ./services/backend/db
          target: /app/db
        - action: sync
          path: ./services/backend/generated
          target: /app/generated
        - action: sync
          path: ./services/backend/internal
          target: /app/internal
        - action: rebuild
          path: ./services/backend/go.mod
        - action: rebuild
          path: ./services/backend/go.sum

  web:
    build:
      context: ./web
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production