services:
  backend:
    build:
      context: ./services/backend
    volumes:
      - ./data/downloads:/app/data/downloads:Z
      - ./data/db:/app/data/db:Z
      - ./data/cache:/app/cache:Z
    user: "${CURRENT_UID}:${CURRENT_GID}"
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - PORT=:8080
      - WS_PORT=:8081
      - DOWNLOAD_PATH=/app/data/downloads
      - DATABASE_PATH=/app/data/db/video-archiver.db
      - DEBUG=${DEBUG:-false}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
      - XDG_CACHE_HOME=/app/cache

  web:
    build:
      context: ./web
      args:
        - NEXT_PUBLIC_SERVER_URL=http://localhost:8080
        - NEXT_PUBLIC_SERVER_URL_WS=ws://localhost:8081
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
