services:
  backend:
    build:
      context: ./services/backend
    volumes:
      - ./downloads:/app/downloads
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production