services:
  backend:
    build:
      context: ./services/backend
    volumes:
      - ./data/downloads:/app/data/downloads
      - ./data/db:/app/data/db
      - ./data/cache:/app/cache
    user: "${CURRENT_UID}:${CURRENT_GID}"
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - PORT=:8080
      - WS_PORT=:8081
      - DOWNLOAD_PATH=/app/data/downloads
      - DATABASE_PATH=/app/data/db/video-archiver.db
      - DEBUG=${DEBUG:-false}
      - XDG_CACHE_HOME=/app/cache

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production