services:
  backend:
    build:
      context: ./services/backend
    volumes:
      - ./data/downloads:/app/data/downloads
      - ./data/db:/app/data/db
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DOWNLOAD_PATH=/app/data/downloads
      - DATABASE_PATH=/app/data/db/video-archiver.db

  web:
    build:
      context: ./web
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production