// Code generated by tygo. DO NOT EDIT.

//////////
// source: job.go

export type JobStatus = string;
export const JobStatusPending: JobStatus = "pending";
export const JobStatusInProgress: JobStatus = "in_progress";
export const JobStatusComplete: JobStatus = "complete";
export const JobStatusError: JobStatus = "error";
export const JobStatusCancelled: JobStatus = "cancelled";
export interface Job {
  id: string;
  url: string;
  status: JobStatus;
  progress: number /* float64 */;
  custom_quality?: number /* int */;
  warnings?: string[];
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}

export type JobRepository = any;
export type JobType = string;
export const JobTypeVideo: JobType = "video";
export const JobTypeAudio: JobType = "audio";
export const JobTypeMetadata: JobType = "metadata";
/**
 * deprecated, remove in the future
 */
export interface JobWithMetadata {
  job?: Job;
  metadata?: Metadata;
}
export interface ProgressUpdate {
  jobID: string;
  jobType: string;
  status?: JobStatus;
  currentItem: number /* int */;
  totalItems: number /* int */;
  progress: number /* float64 */;
  currentVideoProgress: number /* float64 */;
  downloadPhase: string;
  isRetrying?: boolean;
  retryCount?: number /* int */;
  maxRetries?: number /* int */;
  retryError?: string;
  warnings?: string[];
}
export const DownloadPhaseMetadata = "metadata";
export const DownloadPhaseVideo = "video";
export const DownloadPhaseAudio = "audio";
export const DownloadPhaseMerging = "merging";
export const DownloadPhaseComplete = "complete";
export interface VideoMetadata {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  duration: number /* int */;
  duration_string: string;
  view_count: number /* int */;
  like_count: number /* int */;
  comment_count: number /* int */;
  channel: string;
  channel_id: string;
  channel_url: string;
  channel_follower_count: number /* int */;
  channel_is_verified: boolean;
  uploader: string;
  uploader_id: string;
  uploader_url: string;
  tags: string[];
  categories: string[];
  upload_date: string;
  filesize_approx: number /* int64 */;
  format: string;
  ext: string;
  language: string;
  width: number /* int */;
  height: number /* int */;
  resolution: string;
  fps: number /* float64 */;
  dynamic_range: string;
  vcodec: string;
  aspect_ratio: number /* float64 */;
  acodec: string;
  audio_channels: number /* int */;
  was_live: boolean;
  webpage_url_domain: string;
  extractor: string;
  fulltitle: string;
  _type: string;
}
export interface Thumbnail {
  url: string;
  height: number /* int */;
  width: number /* int */;
  id: string;
}
export interface PlaylistItem {
  id: string;
  title: string;
  description?: string;
  thumbnail?: string;
  duration?: number /* int */;
  duration_string?: string;
  upload_date?: string;
  view_count?: number /* int */;
  like_count?: number /* int */;
  video_file?: string;
  channel?: string;
  channel_id?: string;
  channel_url?: string;
  width?: number /* int */;
  height?: number /* int */;
  resolution?: string;
  filesize_approx?: number /* int64 */;
  format?: string;
  ext?: string;
  tags?: string[];
}
export interface PlaylistMetadata {
  id: string;
  title: string;
  description: string;
  thumbnails: Thumbnail[];
  uploader_id: string;
  uploader_url: string;
  channel_id: string;
  channel: string;
  channel_url: string;
  channel_follower_count: number /* int */;
  playlist_count: number /* int */;
  view_count?: number /* int */;
  items?: PlaylistItem[];
  _type: string;
}
export interface ChannelMetadata {
  id: string;
  channel: string;
  channel_url: string;
  description: string;
  thumbnails: Thumbnail[];
  channel_follower_count: number /* int */;
  playlist_count: number /* int */;
  _type: string;
  video_count?: number /* int */;
  total_storage?: number /* int64 */;
  total_views?: number /* int */;
  recent_videos?: PlaylistItem[];
}
export interface MetadataUpdate {
  jobID: string;
  metadata: Metadata;
}
export type Metadata = any;

//////////
// source: settings.go

export interface Settings {
  id: number /* int */;
  theme: string;
  download_quality: number /* int */;
  concurrent_downloads: number /* int */;
  tools_default_format: string;
  tools_default_quality: string;
  tools_preserve_original: boolean;
  tools_output_path: string;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
}

export type SettingsRepository = any;

//////////
// source: statistics.go

export interface Statistics {
  total_jobs: number /* int */;
  total_videos: number /* int */;
  total_playlists: number /* int */;
  total_channels: number /* int */;
  total_storage: number /* int */;
  top_videos: VideoStorageInfo[];
  other_storage: number /* int */;
  last_update: string /* RFC3339 */;
}
export interface VideoStorageInfo {
  title: string;
  size: number /* int */;
  channel: string;
}

//////////
// source: tools.go

export type ToolsJobStatus = string;
export const ToolsJobStatusPending: ToolsJobStatus = "pending";
export const ToolsJobStatusProcessing: ToolsJobStatus = "processing";
export const ToolsJobStatusComplete: ToolsJobStatus = "complete";
export const ToolsJobStatusFailed: ToolsJobStatus = "failed";
export const ToolsJobStatusCancelled: ToolsJobStatus = "cancelled";
export type ToolsOperationType = string;
export const OpTypeTrim: ToolsOperationType = "trim";
export const OpTypeConcat: ToolsOperationType = "concat";
export const OpTypeConvert: ToolsOperationType = "convert";
export const OpTypeExtractAudio: ToolsOperationType = "extract_audio";
export const OpTypeAdjustQuality: ToolsOperationType = "adjust_quality";
export const OpTypeRotate: ToolsOperationType = "rotate";
export const OpTypeWorkflow: ToolsOperationType = "workflow";
/**
 * ToolsInputType describes how InputFiles should be interpreted.
 */
export type ToolsInputType = string;
export const InputTypeVideos: ToolsInputType = "videos";
export const InputTypePlaylist: ToolsInputType = "playlist";
export const InputTypeChannel: ToolsInputType = "channel";
/**
 * ToolsJob represents a single media-processing job operating on already
 * downloaded videos. InputFiles holds download job IDs (videos, or a single
 * playlist/channel that is expanded into its videos).
 */
export interface ToolsJob {
  id: string;
  operation_type: ToolsOperationType;
  status: ToolsJobStatus;
  progress: number /* float64 */; // 0-100
  input_files: string[];
  input_type: ToolsInputType;
  output_file: string;
  parameters: { [key: string]: any};
  error_message?: string;
  created_at: string /* RFC3339 */;
  updated_at: string /* RFC3339 */;
  completed_at?: string /* RFC3339 */;
  estimated_size?: number /* int64 */;
  actual_size?: number /* int64 */;
}
export interface TrimParameters {
  start_time: string; // HH:MM:SS(.ms) or seconds
  end_time: string; // HH:MM:SS(.ms) or seconds
  re_encode: boolean; // Re-encode for frame-accurate cuts
}
export interface ConcatParameters {
  output_format: string; // mp4, mkv, webm
  re_encode: boolean; // Re-encode if codecs differ
  file_order: string[]; // Explicit ordering by job ID
}
export interface ConvertParameters {
  output_format: string; // mp4, webm, mkv, avi, mov
  video_codec: string; // libx264, libx265, libvpx-vp9, copy
  audio_codec: string; // aac, libmp3lame, libopus, copy
  bitrate: string; // e.g. "2M", "5M"
}
export interface ExtractAudioParameters {
  output_format: string; // mp3, aac, flac, wav, ogg
  bitrate: string; // e.g. "128k", "320k"
  sample_rate: number /* int */; // e.g. 44100, 48000
}
export interface AdjustQualityParameters {
  resolution: string; // 480p, 720p, 1080p, ...
  bitrate: string; // optional target bitrate
  crf: number /* int */; // Constant Rate Factor (0-51)
  two_pass: boolean; // Two-pass encoding (requires bitrate)
}
export interface RotateParameters {
  rotation: number /* int */; // 0, 90, 180, 270
  flip_h: boolean; // Horizontal flip
  flip_v: boolean; // Vertical flip
}
export interface WorkflowParameters {
  steps: WorkflowStep[];
  keep_intermediate_files: boolean;
  stop_on_error: boolean;
}
export interface WorkflowStep {
  operation: ToolsOperationType;
  parameters: { [key: string]: any};
  output_name?: string;
}
/**
 * ToolsProgressUpdate is broadcast over the WebSocket as a job runs. The Type
 * field lets the frontend route the message without fragile field sniffing.
 */
export interface ToolsProgressUpdate {
  type: string; // always "tools-progress"
  jobID: string;
  status: ToolsJobStatus;
  progress: number /* float64 */;
  current_step: string;
  time_elapsed: number /* int */; // seconds
  time_remaining: number /* int */; // estimated seconds
  error?: string;
}

export type ToolsRepository = any;
