import { toolOutputUrl, toolThumbnailUrl } from '@/services/toolsApi'
import { ToolsJob } from '@/types'
import { Download, Film, Music, Play, Trash2 } from 'lucide-react'

import { useState } from 'react'

import { formatBytes, formatSeconds } from '@/lib/utils'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'

import {
    formatDate,
    mediaKindOf,
    operationLabel,
    outputFilename,
} from './processedMedia'

interface ProcessedMediaCardProps {
    job: ToolsJob
    /** Marks the job that just finished in this session. */
    isNew: boolean
    onPreview: (job: ToolsJob) => void
    onDelete: (job: ToolsJob) => void
}

/**
 * ProcessedMediaCard shows one tool output as a thumbnail card: a poster frame
 * for video outputs (generated by the backend), an icon tile for audio, plus
 * the probed metadata and download/delete actions.
 */
export function ProcessedMediaCard({
    job,
    isNew,
    onPreview,
    onDelete,
}: ProcessedMediaCardProps) {
    const kind = mediaKindOf(job)
    // Legacy jobs without probed metadata may have no thumbnail on the
    // backend; fall back to the icon tile when the image request fails.
    const [thumbFailed, setThumbFailed] = useState(false)
    const filename = outputFilename(job)
    const extension = filename.split('.').pop()?.toUpperCase() ?? ''
    const KindIcon = kind === 'audio' ? Music : Film

    return (
        <Card
            className={`overflow-hidden border pt-0 transition-all hover:shadow-md ${
                isNew ? 'ring-primary/50 border-primary/50 ring-1' : ''
            }`}
        >
            <div className="bg-muted group relative aspect-video">
                {kind === 'video' && !thumbFailed ? (
                    <img
                        src={toolThumbnailUrl(job.id)}
                        alt={filename || 'Processed video'}
                        loading="lazy"
                        className="absolute inset-0 h-full w-full object-cover"
                        onError={() => setThumbFailed(true)}
                    />
                ) : (
                    <div className="absolute inset-0 flex items-center justify-center">
                        <KindIcon className="text-muted-foreground h-10 w-10 opacity-60" />
                    </div>
                )}
                {isNew && (
                    <Badge className="absolute top-2 left-2 z-10 text-xs">
                        Just processed
                    </Badge>
                )}
                {(job.duration ?? 0) > 0 && (
                    <div className="absolute right-2 bottom-2 rounded bg-black/70 px-1 text-xs text-white">
                        {formatSeconds(job.duration ?? 0)}
                    </div>
                )}
                <button
                    type="button"
                    aria-label={`Preview ${filename}`}
                    onClick={() => onPreview(job)}
                    className="absolute inset-0 flex cursor-pointer items-center justify-center bg-black/20 opacity-0 transition-opacity group-hover:opacity-100 focus-visible:opacity-100"
                >
                    <span className="flex h-12 w-12 items-center justify-center rounded-full bg-black/50 text-white transition-colors hover:bg-black/70">
                        <Play className="h-6 w-6" />
                    </span>
                </button>
            </div>
            <CardContent className="px-4 pt-2">
                <div className="flex items-center gap-2">
                    <KindIcon className="text-muted-foreground h-4 w-4 shrink-0" />
                    <h3 className="line-clamp-1 text-sm font-semibold">
                        {operationLabel(job.operation_type)}
                    </h3>
                </div>
                <p className="text-muted-foreground mt-1 truncate text-xs">
                    {filename}
                </p>
                <p className="text-muted-foreground text-xs">
                    {formatDate(job.completed_at || job.updated_at)}
                </p>
                <div className="mt-3 flex flex-wrap items-center gap-2">
                    {(job.height ?? 0) > 0 && (
                        <Badge variant="outline" className="text-xs">
                            {job.height}p
                        </Badge>
                    )}
                    {extension && (
                        <Badge variant="outline" className="text-xs">
                            {extension}
                        </Badge>
                    )}
                    {(job.actual_size ?? 0) > 0 && (
                        <Badge variant="outline" className="text-xs">
                            {formatBytes(job.actual_size ?? 0)}
                        </Badge>
                    )}
                </div>
                <div className="mt-3 flex items-center justify-between">
                    <Button asChild variant="outline" size="sm">
                        <a
                            href={toolOutputUrl(job.id)}
                            download={filename || true}
                        >
                            <Download className="mr-1 h-4 w-4" />
                            Download
                        </a>
                    </Button>
                    <Button
                        variant="ghost"
                        size="icon"
                        className="text-destructive hover:text-destructive"
                        aria-label="Delete processed file"
                        onClick={() => onDelete(job)}
                    >
                        <Trash2 className="h-4 w-4" />
                    </Button>
                </div>
            </CardContent>
        </Card>
    )
}
