name: Build and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_lint_nextjs:
    runs-on: ubuntu-latest
    name: Build and Lint Next.js App

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          cd web
          pnpm install

      - name: Lint Next.js
        run: |
          cd web
          pnpm run lint

      - name: Build Next.js
        run: |
          cd web
          pnpm run build

  build_and_lint_go:
    runs-on: ubuntu-latest
    name: Build and Lint Go Backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Install Go dependencies
        run: |
          cd services/backend
          go mod download

      - name: Lint Go code
        run: |
          cd services/backend
          go fmt ./...
          go vet ./...

      - name: Build Go
        run: |
          cd services/backend
          go build ./...
